//
// Created by kate on 7/10/2023.
//

#ifndef VULKATE_VULKAN_PRESET_PIPELINE_CONFIGURATIONS_HH
#define VULKATE_VULKAN_PRESET_PIPELINE_CONFIGURATIONS_HH

namespace kaTe {

}
#endif //VULKATE_VULKAN_PRESET_PIPELINE_CONFIGURATIONS_HH
