# Engine Configuration File for Mikoto
# This file contains settings and configurations for the engine.
# All paths MUST BE RELATIVE to the executable path.

[engine]
name = "Mikoto - Engine"           # Name of the engine
version = "1.0.0"                  # Engine version

[paths]
assets = ""                # Path to the assets folder
shaders = ""       # Path to the shaders folder
textures = "."     # Path to the textures folder
imgui_config = "" # Path to the ImGui configuration file
shaders = "" # Path to the shaders
icons = "" # Path to the icons
fonts = "" # Path to the fonts
logs = ""                    # Path to store log files

[renderer]
api = "vulkan"                     # Rendering API (vulkan)
vsync = true                       # Enable/disable VSync

[window]
title = "Mikoto - Engine Vulkan"         # Window title
width = 1920                       # Window width in pixels
height = 1080                       # Window height in pixels
resizable = true                   # Allow resizing the window (true/false)

[imgui]
enable = true                      # Enable or disable ImGui (true/false)
theme = "dark"                     # ImGui theme (dark, light, classic), used for startup

[resources]

[logging]

[input]
mouse_translate_sensitivity = 1.0            # Mouse sensitivity (movement)
mouse_rotate_sensitivity = 1.0            # Mouse sensitivity (rotation)
invert_y_axis = false              # Invert Y-axis for the camera (true/false)

[debug]
show_fps = true                    # Show FPS counter on the screen
draw_debug_overlay = false         # Draw debug overlay