name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake vulkan-tools libvulkan-dev vulkan-validationlayers-dev spirv-tools libglfw3-dev libgtk-3-dev

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cd build && cmake ..

    - name: Build
      run: cd build && cmake --build .

    - name: Run tests
      run: cd build && ctest
